---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ17N18"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true
  Acceptance:
    cloudFoundryDeploy: false
    npmExecuteEndToEndTests: false
  Malware Scan:
    malwareExecuteScan: true
  Release:
    tmsExport: false
    tmsUpload: false
    cloudFoundryDeploy: false
  Additional Unit Tests:
    npmExecuteScripts: true
  Compliance:
    sonarExecuteScan: false
steps:
  npmExecuteLint:
    failOnError: false
  npmExecuteScripts:
    runScripts:
    - "test"
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
